import os

import docker

REGISTRY_URL = "localhost:5000"
DOCKER_URL = "unix://var/run/docker.sock"

api_client = docker.APIClient(base_url=DOCKER_URL)
docker_client = docker.DockerClient(base_url=DOCKER_URL)
API_URL = "http://172.18.0.1:3000"
API_USER = ""
API_PASSWORD = ""
EXECUTION_ID = ""

image = ""

params = "beyJhc3NldCI6ICJ1c2Vycy9nZWZsYW5kZGVncmFkYXRpb24vdG9vbGJveF9kYXRhc2V0cy9uZHZpX21vZGlzXzIwMDFfMjAxOSIsICJjcm9zc2VzXzE4MHRoIjogZmFsc2UsICJjcnMiOiAiR0VPR0NTW1wiV0dTIDg0XCIsREFUVU1bXCJXR1NfMTk4NFwiLFNQSEVST0lEW1wiV0dTIDg0XCIsNjM3ODEzNywyOTguMjU3MjIzNTYzLEFVVEhPUklUWVtcIkVQU0dcIixcIjcwMzBcIl1dLEFVVEhPUklUWVtcIkVQU0dcIixcIjYzMjZcIl1dLFBSSU1FTVtcIkdyZWVud2ljaFwiLDAsQVVUSE9SSVRZW1wiRVBTR1wiLFwiODkwMVwiXV0sVU5JVFtcImRlZ3JlZVwiLDAuMDE3NDUzMjkyNTE5OTQzMyxBVVRIT1JJVFlbXCJFUFNHXCIsXCI5MTIyXCJdXSxBVVRIT1JJVFlbXCJFUFNHXCIsXCI0MzI2XCJdXSIsICJnZW9qc29ucyI6ICJbe1widHlwZVwiOiBcIlBvbHlnb25cIiwgXCJjb29yZGluYXRlc1wiOiBbW1szNi42NzYyNDIzMDMzMzk2OCwgLTEuNDE3MTIyNDkwODEwM10sIFszNy4xMzE1MTE2NzIyMjU4ODQsIC0xLjQxNzEyMjQ5MDgxMDNdLCBbMzcuMTMxNTExNjcyMjI1ODg0LCAtMS4xMzkzNjE2NjcxMDcyMzhdLCBbMzYuNjc2MjQyMzAzMzM5NjgsIC0xLjEzOTM2MTY2NzEwNzIzOF0sIFszNi42NzYyNDIzMDMzMzk2OCwgLTEuNDE3MTIyNDkwODEwM11dXX1dIiwgIm5hbWUiOiAiTU9ESVMgKE1PRDEzUTEsIGFubnVhbCkiLCAidGFza19uYW1lIjogIm1vZGlzXzFfNDAiLCAidGFza19ub3RlcyI6ICIiLCAidGVtcG9yYWxfcmVzb2x1dGlvbiI6ICJhbm51YWwiLCAieWVhcl9lbmQiOiAyMDE1LCAieWVhcl9zdGFydCI6IDIwMDF9"

GOOGLE_STORAGE_BUCKET = "eldmt"
EE_SERVICE_ACCOUNT_JSON = os.getenv("EE_SERVICE_ACCOUNT_JSON")
ROLLBAR_SCRIPT_TOKEN = os.getenv("ROLLBAR_SCRIPT_TOKEN")

env = {"GOOGLE_STORAGE_BUCKET": GOOGLE_STORAGE_BUCKET, "EE_SERVICE_ACCOUNT_JSON": EE_SERVICE_ACCOUNT_JSON,
       "ROLLBAR_SCRIPT_TOKEN": ROLLBAR_SCRIPT_TOKEN, "API_URL": API_URL, "API_USER": API_USER,
       "API_PASSWORD": API_PASSWORD, "EXECUTION_ID": EXECUTION_ID, "ENV": "dev"}

docker_client.containers.run(image=REGISTRY_URL + '/' + image, command=params, environment=env, detach=True)
